---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    target: registry
    component: registry
spec:
  selector:
    target: registry
    component: registry
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
