---
apiVersion: v1
kind: Service
metadata:
  name: product-price-database
  labels:
    target: product-price
    component: mongodb
spec:
  selector:
    target: product-price
    component: mongodb
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
