#!/usr/bin/env ruby

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new do |task|
  task.libs << ["lib"]
  task.pattern = File.join(__dir__, "test/**/test_*.rb")
end

task :default => :test
